# Generated by Django 5.2.13 on 2026-04-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(choices=[('BG', 'Bulgaria'), ('UK', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('ES', 'Spain'), ('IT', 'Italy'), ('US', 'United States'), ('OTHER', 'Other')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('travelers', models.ManyToManyField(blank=True, related_name='destinations', to='travelers.traveler')),
            ],
            options={
                'unique_together': {('name', 'country')},
            },
        ),
    ]
