# Generated by Django 5.2.10 on 2026-02-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
