# Generated by Django 5.0.4 on 2026-06-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
