# Generated by Django 5.2.13 on 2026-04-27 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_verified', models.BooleanField(default=False)),
                ('review_type', models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travelers.traveler')),
            ],
        ),
    ]
